-- Reinisch Classroom local E2E certification schema.
--
-- LOCAL TEST USE ONLY.
-- This file is intentionally outside supabase/migrations so it is never part
-- of the production migration chain.
--
-- Execution requires:
--   SET rc.local_e2e = '1';
--
-- The schema follows the CURRENT APPLICATION RUNTIME CONTRACT rather than
-- replaying contradictory historical repository migrations.

DO $$
BEGIN
  IF current_setting('rc.local_e2e', true) IS DISTINCT FROM '1' THEN
    RAISE EXCEPTION
      'REFUSING TO RUN: rc.local_e2e must be explicitly set to 1';
  END IF;
END
$$;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;

-- ---------------------------------------------------------------------------
-- Deterministic local reset.
-- Safe only after the rc.local_e2e guard above succeeds.
-- ---------------------------------------------------------------------------

DROP TABLE IF EXISTS public.goal_data_points CASCADE;
DROP TABLE IF EXISTS public.goal_progress CASCADE;
DROP TABLE IF EXISTS public.submission_answers CASCADE;
DROP TABLE IF EXISTS public.submissions CASCADE;
DROP TABLE IF EXISTS public.assignment_item_mappings CASCADE;
DROP TABLE IF EXISTS public.assignment_items CASCADE;
DROP TABLE IF EXISTS public.assignment_instances CASCADE;
DROP TABLE IF EXISTS public.assignments CASCADE;
DROP TABLE IF EXISTS public.goals CASCADE;
DROP TABLE IF EXISTS public.enrollments CASCADE;
DROP TABLE IF EXISTS public.class_enrollments CASCADE;
DROP TABLE IF EXISTS public.students CASCADE;
DROP TABLE IF EXISTS public.classes CASCADE;
DROP TABLE IF EXISTS public.teacher_drafts CASCADE;
DROP TABLE IF EXISTS public.teacher CASCADE;
DROP TABLE IF EXISTS public.app_users CASCADE;

-- ---------------------------------------------------------------------------
-- Authentication support
-- ---------------------------------------------------------------------------

CREATE TABLE public.app_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  role text NOT NULL
    CHECK (role IN ('student', 'teacher', 'substitute', 'admin')),

  -- Historical auth RPCs expose this as bigint. Current classroom students use
  -- UUID IDs, so local E2E deliberately leaves this nullable and unlinked.
  student_id bigint,

  password_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.verify_student_password(
  p_code text,
  p_password text
)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.app_users
    WHERE username = upper(trim(p_code))
      AND role = 'student'
      AND password_hash = extensions.crypt(p_password, password_hash)
  );
$$;

CREATE OR REPLACE FUNCTION public.verify_user_password(
  p_username text,
  p_password text
)
RETURNS TABLE(
  username text,
  role text,
  student_id bigint,
  user_id bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, extensions
AS $$
DECLARE
  v_user public.app_users%ROWTYPE;
BEGIN
  SELECT *
  INTO v_user
  FROM public.app_users
  WHERE app_users.username = p_username;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  IF v_user.password_hash =
     extensions.crypt(p_password, v_user.password_hash)
  THEN
    RETURN QUERY
    SELECT
      v_user.username,
      v_user.role,
      v_user.student_id,
      v_user.id;
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- Teacher Work drafts
-- ---------------------------------------------------------------------------

CREATE TABLE public.teacher_drafts (
  id text PRIMARY KEY,
  teacher text NOT NULL DEFAULT 'default',
  title text NOT NULL,
  class_name text,
  release_at timestamptz,
  due_at timestamptz,
  notes text,
  assignment jsonb NOT NULL DEFAULT '{}'::jsonb,
  mapping jsonb NOT NULL DEFAULT '{}'::jsonb,
  auto_release boolean NOT NULL DEFAULT false,
  issued_at timestamptz,
  auto_release_status text NOT NULL DEFAULT 'pending'
    CHECK (
      auto_release_status IN (
        'pending',
        'issued',
        'errored',
        'disabled'
      )
    ),
  auto_release_error text,
  auto_release_attempted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_teacher_drafts_teacher
  ON public.teacher_drafts(teacher);

CREATE INDEX idx_teacher_drafts_updated
  ON public.teacher_drafts(updated_at DESC);

CREATE INDEX idx_teacher_drafts_auto_release_due
  ON public.teacher_drafts(release_at)
  WHERE
    auto_release = true
    AND auto_release_status = 'pending'
    AND issued_at IS NULL;

-- ---------------------------------------------------------------------------
-- Teacher / class / student
-- ---------------------------------------------------------------------------

CREATE TABLE public.teacher (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id uuid NOT NULL UNIQUE,
  teacher_code text NOT NULL UNIQUE,
  username text,
  full_name text,
  first_name text,
  last_name text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.classes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text UNIQUE,
  name text NOT NULL,
  teacher_id uuid NOT NULL
    REFERENCES public.teacher(id)
    ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_classes_name_teacher UNIQUE (name, teacher_id)
);

CREATE TABLE public.students (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text,
  class_id uuid
    REFERENCES public.classes(id)
    ON DELETE SET NULL,
  class_code text,
  active boolean NOT NULL DEFAULT true,
  iep_due date,
  eval_due date,
  primary_case_manager text,
  archived_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.class_enrollments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  class_id uuid NOT NULL
    REFERENCES public.classes(id)
    ON DELETE CASCADE,
  student_id uuid NOT NULL
    REFERENCES public.students(id)
    ON DELETE CASCADE,
  class_code text,
  enrolled_at timestamptz NOT NULL DEFAULT now(),
  start_date date NOT NULL DEFAULT CURRENT_DATE,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (class_id, student_id)
);

-- Compatibility fallback used by teacher-issue-draft.
CREATE TABLE public.enrollments (
  student_code text NOT NULL,
  class_id uuid NOT NULL
    REFERENCES public.classes(id)
    ON DELETE CASCADE,
  start_date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (student_code, class_id)
);

-- ---------------------------------------------------------------------------
-- Assignments
-- ---------------------------------------------------------------------------

CREATE TABLE public.assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  section text DEFAULT 'language-arts',
  due_date date,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),

  -- Runtime accepts values such as html/txt without requiring historical enum.
  type text NOT NULL DEFAULT 'html',

  series text,
  page text,
  hero text,
  meta jsonb DEFAULT '{}'::jsonb,
  created_by text,
  class_id uuid
    REFERENCES public.classes(id)
    ON DELETE SET NULL,

  first_submission_at timestamptz,
  version_locked boolean NOT NULL DEFAULT false,
  source_type text NOT NULL DEFAULT 'portal'
    CHECK (source_type IN ('portal', 'google_form', 'import')),
  school_year integer,
  finalized_at timestamptz
);

CREATE TABLE public.assignment_instances (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  assignment_id bigint NOT NULL
    REFERENCES public.assignments(id)
    ON DELETE CASCADE,
  student_id uuid NOT NULL
    REFERENCES public.students(id)
    ON DELETE CASCADE,
  assigned_at date NOT NULL DEFAULT CURRENT_DATE,
  due_at date,
  status text NOT NULL DEFAULT 'Assigned',
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  resubmission_count integer NOT NULL DEFAULT 0,
  school_year integer,
  UNIQUE (assignment_id, student_id)
);

CREATE TABLE public.assignment_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id bigint NOT NULL
    REFERENCES public.assignments(id)
    ON DELETE CASCADE,
  item_ref text NOT NULL,
  answer_type text NOT NULL
    CHECK (
      answer_type IN (
        'mcq',
        'multi',
        'boolean',
        'constructed',
        'written_response'
      )
    ),
  points numeric NOT NULL DEFAULT 1
    CHECK (points >= 0),
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  goal_codes text[] NOT NULL DEFAULT ARRAY[]::text[],
  dese_codes text[] NOT NULL DEFAULT ARRAY[]::text[],
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (assignment_id, item_ref)
);

-- Current runtime joins this bigint item_id to assignment_items.id.
CREATE TABLE public.assignment_item_mappings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id bigint NOT NULL
    REFERENCES public.assignment_items(id)
    ON DELETE CASCADE,
  dese_codes text[] NOT NULL DEFAULT ARRAY[]::text[],
  goal_codes text[] NOT NULL DEFAULT ARRAY[]::text[],
  weight numeric NOT NULL DEFAULT 1.0
    CHECK (weight >= 0 AND weight <= 1),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (item_id)
);

-- ---------------------------------------------------------------------------
-- Submission / grading
-- ---------------------------------------------------------------------------

CREATE TABLE public.submissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  instance_id uuid NOT NULL
    REFERENCES public.assignment_instances(id)
    ON DELETE CASCADE,
  submitted_at timestamptz NOT NULL DEFAULT now(),
  answers jsonb DEFAULT '{}'::jsonb,
  score_auto numeric,
  score_manual numeric,
  score_total numeric,
  detail jsonb,
  notes text,
  original_submission_id uuid
    REFERENCES public.submissions(id)
    ON DELETE SET NULL,
  submission_type text NOT NULL DEFAULT 'initial'
    CHECK (submission_type IN ('initial', 'resubmission')),
  source_type text NOT NULL DEFAULT 'portal'
    CHECK (source_type IN ('portal', 'google_form', 'import')),
  review_status text NOT NULL DEFAULT 'pending'
    CHECK (
      review_status IN (
        'pending',
        'in_progress',
        'reviewed',
        'finalized',
        'returned'
      )
    ),
  graded_at timestamptz,
  graded_by text,
  feedback text,
  school_year integer
);

CREATE INDEX idx_submissions_instance
  ON public.submissions(instance_id);

CREATE TABLE public.submission_answers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  submission_id uuid NOT NULL
    REFERENCES public.submissions(id)
    ON DELETE CASCADE,
  assignment_item_id bigint NOT NULL
    REFERENCES public.assignment_items(id)
    ON DELETE CASCADE,
  raw_answer jsonb,
  is_correct boolean,
  earned_points numeric,
  max_points numeric,
  teacher_note text,
  rationale text,
  ai_suggested_score numeric,
  scored_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (submission_id, assignment_item_id)
);

CREATE INDEX idx_submission_answers_submission_id
  ON public.submission_answers(submission_id);

CREATE INDEX idx_submission_answers_item_id
  ON public.submission_answers(assignment_item_id);

-- ---------------------------------------------------------------------------
-- Goals / progress evidence
-- ---------------------------------------------------------------------------

CREATE TABLE public.goals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_id uuid
    REFERENCES public.students(id)
    ON DELETE CASCADE,
  code text,
  "desc" text,
  description text,
  target text,
  status text NOT NULL DEFAULT 'Open',
  version integer NOT NULL DEFAULT 1,
  active boolean NOT NULL DEFAULT true,
  replaced_by uuid
    REFERENCES public.goals(id)
    ON DELETE SET NULL,
  start_date date,

  goal_area text,
  area text,
  skill_area text,

  baseline text,
  mastery text,
  measurement_type text NOT NULL DEFAULT 'percent',
  class_context text,
  case_manager text,
  data_collector text,
  data_collector_email text,
  observation_config jsonb,
  notes text,
  addressed_in_class boolean NOT NULL DEFAULT true,
  individual_delivery boolean NOT NULL DEFAULT false,

  created_at timestamptz NOT NULL DEFAULT now(),

  UNIQUE (student_id, code)
);

CREATE TABLE public.goal_progress (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  goal_id uuid NOT NULL
    REFERENCES public.goals(id)
    ON DELETE CASCADE,
  student_id uuid NOT NULL
    REFERENCES public.students(id)
    ON DELETE CASCADE,
  class_id uuid
    REFERENCES public.classes(id)
    ON DELETE SET NULL,
  date date NOT NULL,
  value numeric NOT NULL
    CHECK (value >= 0 AND value <= 100),
  source text NOT NULL DEFAULT 'manual'
    CHECK (source IN ('manual', 'assignment', 'import')),
  assignment_instance_id uuid
    REFERENCES public.assignment_instances(id)
    ON DELETE SET NULL,
  collected_by text,
  school_year integer,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_goal_progress_assignment_instance
  ON public.goal_progress(assignment_instance_id);

CREATE TABLE public.goal_data_points (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  goal_id uuid NOT NULL
    REFERENCES public.goals(id)
    ON DELETE CASCADE,
  student_id uuid NOT NULL
    REFERENCES public.students(id)
    ON DELETE CASCADE,
  assignment_instance_id uuid
    REFERENCES public.assignment_instances(id)
    ON DELETE SET NULL,
  item_id bigint
    REFERENCES public.assignment_items(id)
    ON DELETE SET NULL,
  question_text text,
  choices jsonb,
  student_answer text,
  correct_answer text,
  is_correct boolean,
  score numeric,
  date date NOT NULL,
  source text NOT NULL DEFAULT 'assignment'
    CHECK (source IN ('assignment', 'manual')),
  school_year text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Local REST access
--
-- Netlify server functions use the local service-role key.
-- Teacher Review also performs direct anon-key reads for structural metadata.
-- These grants apply ONLY to this guarded standalone E2E database.
-- ---------------------------------------------------------------------------

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

GRANT SELECT ON
  public.assignment_items,
  public.assignment_item_mappings
TO anon, authenticated;

GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

GRANT EXECUTE
  ON FUNCTION public.verify_student_password(text, text)
TO anon, authenticated, service_role;

GRANT EXECUTE
  ON FUNCTION public.verify_user_password(text, text)
TO anon, authenticated, service_role;

NOTIFY pgrst, 'reload schema';
